### ISSUE TITLE
incorrect link for why stack views are good

### ISSUE THREAD

**Issue by chrisdrackett** [snackui/snackui#2]
the link here (https://github.com/snackui/snackui/blame/master/README.md#L100) is to https://github.com/jsxstyle/jsxstyle#why-write-styles-inline-with-jsxstyle but I assume you wanted to link to something talking about the benefits of stack views

**Comment by natew** [comment]
Yea, this is poorly written. What I want to link to is why inline styles are better, and separately I should link to something nice on stack views.

**Comment by natew** [comment]
Should be clearer now.
