### ISSUE TITLE
use Pressable for native instead of having an extra TouchableOpacity

### ISSUE THREAD

**Issue by chrisdrackett** [snackui/snackui#4]
There might be a reason for using `TouchableOpacity` that I'm missing, but if not using the newish `Pressable` component from react native (https://reactnative.dev/docs/pressable) should simplify the stack a bit on native.

**Comment by natew** [comment]
I'll test it out, won't I have to create a new TouchableOpacity based on Pressable to get the touch effect?

**Comment by natew** [comment]
Ah yea, makes sense, I missed it was used in Stacks. Will look into changing that.

**Comment by natew** [comment]
As of 0.4.1 stacks use Pressable by default.

**Comment by coycoylaniba** [comment]
@natew but i don't think stacks have function type children unlike pressable.
