### ISSUE TITLE
[Question] Next SSR support

### ISSUE THREAD

**Issue by macieklad** [snackui/snackui#7]
Hello, I was interested to try snackui with a project, in which we use next with expo as our web platform. I saw the information about no SSR support, and I was curious what problem there is to solve, maybe I could contribute a solution.

**Comment by natew** [comment]
There's no reason it shouldn't work with SSR I believe, I just am not sure if it *does* in practice. One first good step would be go set up a simple example in the examples folder for SSR, and just see what happens first try. I believe we had SSR working somewhat previously even.

So it's more an unknown if it works or not, but I don't see any reason it shouldn't. Let me know if you have any questions, happy to help.

**Comment by natew** [comment]
Added useIsomorphicLayoutEffect which I know should help, released in 0.7.0. I'll look at an example sometime soon.
