### ISSUE TITLE
Just wanted to say amazing work

### ISSUE THREAD

**Issue by Cavitt** [snackui/snackui#9]
Found your project from your comment on HN the other day.
I wanted to say I love the project and I believe you're on the right track.

Currently the RN cross-platform style ecosystem is limited, this project is the first that combines atomic CSS, types, media queries, psuedo selector support, theming, all while working with RN(W) stylesheets.

Keep up the good work, I'm following along and I hope to contribute where I can.

**Comment by natew** [comment]
Means more than you think!

Honestly, just knowing what people are interested in next would be helpful. Any ideas, feel free to open a discussion.
